% retain only the necessary variables in the database
clearvars -except basic_data coor elem_data dest_array connectivity ...
bound bound_vals bound_amplitudes ...
force force_vals force_amplitudes ...
mat_data amplitude_data step_data ...
full_solution stress strain ivar reac ...
Kg Fg Kgprime rhsprime;